### ISSUE TITLE
CheckBoxes are clipped in the TCheckListBox controls

### ISSUE THREAD

**Issue by furious-programming** [zamtmn/metadarkstyle#11]
Comparison between the dark and classic Lazarus:

![image](https://user-images.githubusercontent.com/8170730/231617904-ac09a80a-e276-4096-8913-bf4cf076776f.png)

CheckBox background is good but the frame and tick are shifted few pixels to the left side.

**Comment by zamtmn** [comment]
related https://github.com/zamtmn/metadarkstyle/issues/2

**Comment by zamtmn** [comment]
I didn't understand where this window was. please check after https://github.com/zamtmn/metadarkstyle/commit/a65a6b8c327f24282b8f9cf2815d4bca9e565457

**Comment by furious-programming** [comment]
> I didn't understand where this window was.

It is available if the project have many build modes:

![image](https://user-images.githubusercontent.com/8170730/232623247-ce0f5589-6387-4a6e-81fc-3125c3047839.png)

But the `TCheckListBox` controls is used in many other places, for example in the `Project Options` window:

![image](https://user-images.githubusercontent.com/8170730/232623417-e785d71d-7c78-48eb-afe8-963080b64c7c.png)

And, as you can see, now they are rendered properly, also in the `Object Inspector` window. So the only missing elements are the color boxes in the `Object Inspector` window, for properties of the type `TColor`.
