### ISSUE TITLE
TComboBox, TMemo in Form Designer 

### ISSUE THREAD

**Issue by RusMikle** [zamtmn/metadarkstyle#13]
In components TComboBox and TMemo, in Form Designer in Design Time, automatically change the background color to dark and the font to light, and so remain after saving. I haven't noticed this problem in other components yet.
I recommend turning off the color scheme change in the form editor altogether.

**Comment by furious-programming** [comment]
Related to the #1 issue. There are many problems related to the designer (form editor), not only colors, but also e.g. expand sign in `TTreeView` is changed explicitely, so it is not possible to get the themed sign.

**Comment by zamtmn** [comment]
Fixed in https://github.com/zamtmn/metadarkstyle/commit/5f029830d05d66d5a22541f2665d9e5425cfa5fa
