### ISSUE TITLE
Q. about latest fix may 22, custom draw scrollbars

### ISSUE THREAD

**Issue by klaus101** [zamtmn/metadarkstyle#19]
@zamtmn: Oh! i see a little problem here. 
First, should we add a small text file that states the purpose of a change in short (whatsnew)?
Here, i would guess it could, may be, done for #9, horizontal scrollbar. Or may it be needed for the color scheme changes?

I think the previous appearance was absolutely good without any need to change it;  Win 10 22H2 x64, Laz. 2.3.
Moreover, it did match established and expected manners, eg. see Win Explorer or Notepad++., whereas the new appearance does not.
What to do if someone (like me) does not like the new appearance? Changing the code manually, merging selectively? For to get the previous behaviour back? I've already a couple of selective adaptions and it becomes more and more complex.

So i'd vote at least for some kind of config switch somewhere (without any need for a gui for such option).
If the change should be done for the recent scheme changes: maybe an option within udarkstyleschemes? Or exclude the new behaviour if DefaultDark is used?

Here it looks as (before  . after)::
![scrolllbar_before](https://github.com/zamtmn/metadarkstyle/assets/31130146/b02fdcdb-52c0-4018-a4aa-8f0bed3b41e3)

![scrollbar_after](https://github.com/zamtmn/metadarkstyle/assets/31130146/0474f4e7-df76-48a8-bcd3-ea078512ef1a)

**Comment by zamtmn** [comment]
Until it's finished, I don't think it's worth describing every step. My ultimate goal is to be able to apply different color schemes. In this regard, it requires the ability to draw all the elements yourself in the desired color. Yes, I think I agree that it is necessary to leave the elements in the system rendering for a dark color by default

**Comment by klaus101** [comment]
Understand,thanks! So, closing.

**Comment by zamtmn** [comment]
Fixed in b28eb76cad50f33afa247b9b4cfe3464f6c15d0a
