### ISSUE TITLE
Statusbar, size grip missing

### ISSUE THREAD

**Issue by klaus101** [zamtmn/metadarkstyle#26]
I'd forgotten to mention. If applicable (eg. Form has borderstyle sizeable, or other criteria), then the StatusBar should have a size grip.
Some ideas about that here:   http://www.devsuperpage.com/Articles/views/Delphi/Art_1-1342.asp

Notepad++ / dark does paint it as shown in this picture:
![size_grip_npp](https://github.com/zamtmn/metadarkstyle/assets/31130146/b446b78e-e48d-43b2-abeb-3748fb8baf2a)

Within the following link there is a panel_sizegrip.zip which shows how it can be painted via themeservices (a 3-liner):
https://forum.lazarus.freepascal.org/index.php/topic,62435.msg472145.html#msg472145
Example (here on a skyblue panel):
![size_grip_painted_themservices](https://github.com/zamtmn/metadarkstyle/assets/31130146/c9d9ea6b-b951-49e2-a1c0-967f6d36b5a3)

**Comment by klaus101** [comment]
Cool!

Maybe the right paddinig after the grip could be reduced a bit```
        //Rect.Left:=Rect.Right-24;
        Rect.Left:=Rect.Right-18;
``
![sizegrip](https://github.com/zamtmn/metadarkstyle/assets/31130146/796ad071-14ff-4cc6-9536-a1aab0ffa929)

**Comment by klaus101** [comment]
After some digging, what could be here the handle for the statusbar theme:
this one should do the job. What do you think?

```
gripSize: TSize;
...
GetThemePartSize(TWin32ThemeServices(ThemeServices).Theme[teStatus],
                 LCanvas.Handle, SP_GRIPPER, 0, @Rect, TS_DRAW, gripSize);
Rect.Left:=Rect.Right - gripSize.cx;
Rect.top:=Rect.Bottom - gripSize.cy;
```
gripSize.cx and gripSize.cy are '16' here.

**Comment by klaus101** [comment]
As it appears to me to be the right solution, i created a pull request.

![sizegrip](https://github.com/zamtmn/metadarkstyle/assets/31130146/bca998e6-d7a8-4936-b8c5-b36db91263b2)

**Comment by klaus101** [comment]
(Merged) .. I thhink this can be closed now

**Comment by klaus101** [comment]
Closing

**Comment by zamtmn** [comment]
Yes, thanks!
