### ISSUE TITLE
PopupMenu: missing indication of focused / hovered items

### ISSUE THREAD

**Issue by klaus101** [zamtmn/metadarkstyle#30]
When hovering items within a TPopupMenu, those hovered resp. focused items should be indicated aomehow by a dedicated background color.
Best for that imo would be something like $00FFAC06 (or some similar synonym).

Actually there is no indication at all (differently to the behaviour in light mode).

Not good if each using instantiation of a popup menu would need to implement ownerdrawing for this basic requirement,

Test project attached.
[_test_PopupMenu.zip](https://github.com/zamtmn/metadarkstyle/files/12134762/_test_PopupMenu.zip)

**Comment by zamtmn** [comment]
I try Your example with metadarkstyle.lpk, not with your files in Darkmode folder
It work:
![image](https://github.com/zamtmn/metadarkstyle/assets/39580611/74f64f01-ad1a-43b7-a23e-252b74d034e8)

With your Darkmode folder, yes, not work.
Please, use package))

**Comment by zamtmn** [comment]
May by you forgot https://github.com/zamtmn/metadarkstyle/issues/16 and near it fix??

**Comment by klaus101** [comment]
Oh yes, thanks for this verification!

Yes, I had some little modifications for some certain reasons, but now I see the culprit.
It is having changed some time ago, within udarkstyleschemes.pas, DefaultDark.SysColor[COLOR_MENUBAR] a bit
....  from RGBToColor(42, 42, 42) to  RGBToColor(66, 66, 66) ....,  and that was unfortunate.
User error, closing …  thank your for attention  

**Comment by klaus101** [comment]
To close by correction of setting
