### ISSUE TITLE
Selected item in inactive TreeView should have background color

### ISSUE THREAD

**Issue by fibodevy** [zamtmn/metadarkstyle#32]
Selected item in TreeView should have some background color when the TreeView is inactive.

You can see for example in Settings, if you are changing some things on the right pane, background of selected category on the left pane disappears (have the same color as default TreeView background color? or transparent). Easy to lose track of where are you in the Settings. Its the same for File Browser, Code Browser and everywhere TreeView is.

Here is an example, I am in the Object Inspector category, but if I didnt know that I would lose track and would need to find out which catergory is that to iterate further.

![MvNMfZloHm](https://github.com/zamtmn/metadarkstyle/assets/21068718/f945599f-1558-4f2c-b97a-deef0972edb3)

**Comment by zamtmn** [comment]
This is the system color drawn by windows for selected item without focus. What color do you propose to paint it?

**Comment by fibodevy** [comment]
I propose it to be customisable, but if it had to be static then just keep the same as it were active

**Comment by zamtmn** [comment]
We have a set of standard colors https://gitlab.com/freepascal.org/lazarus/lazarus/-/blame/main/lcl/lcltype.pp?page=2#L1673 Within this framework, such a setup cannot be done. We have to do the setup of everything and draw everything yourself((

I don't remember exactly, but I think TreeView has a setting so that the out-of-focus element looks the same as in focus

Although it really looks bad. you will have to add a color setting for the tree element

**Comment by fibodevy** [comment]
Here is some fix I made. Maybe you can make something out of it.

```pascal
procedure TForm1.TreeView1CustomDrawItem(Sender: TCustomTreeView; Node: TTreeNode; State: TCustomDrawState; var DefaultDraw: Boolean);
var
  R: TRect;
begin
  DefaultDraw := True;

  if Sender.Focused then exit;

  with Sender as TTreeView do begin
    //only custom draw for selected item
    if not (cdsSelected in State) then exit;

    DefaultDraw := False;

    //draw item background on full row
    Canvas.Brush.Color := Sender.BackgroundColor;
    Canvas.FillRect(Node.DisplayRect(False));

    //draw higlight on either full row or just under the text depending on tvoRowSelect
    Canvas.Brush.Color := clRed; //clHighlight;
    R := Node.DisplayRect(not (tvoRowSelect in Sender.Options));
    if not (tvoRowSelect in Sender.Options) then R.Inflate(-3, 0, -1, 1);
    Canvas.FillRect(R);

    //draw text
    Canvas.Font.Color := clText;
    Canvas.TextOut(Node.DisplayRect(True).Left+4, Node.DisplayRect(True).Top+1, Node.Text);
  end;
end;
```

![bqgCuiMN37](https://github.com/zamtmn/metadarkstyle/assets/21068718/5bc9e946-5542-4b8e-97ff-149270e8d7e3)

**Comment by klaus101** [comment]
And if there are ExpandSign, Icons, StateIcons, TreeLines etc. wanted?
TreeLines and ExpandSign will be removed in the gif sample for selected items. Icons and StateImages would be too,
The problem is, the original paint code (TCustomTreeView.DoPaint in treeview.inc) is 300 lines of code and unfortunately there is no short way to simple redefine a desired background color any item wanted (may be a selected item in unfocused state, or a hovered item).
Imo the dark tool could not be expected to do this full job itself.

**Comment by zamtmn** [comment]
In fact, it's not difficult, we just need to add settings and implement in uWin32WidgetSetDark.DrawThemeBackgroundDark

But in a good way, we need to do a fully customizable rendering of everything, and not selectively what does not suit us

**Comment by fibodevy** [comment]
How about make a copy of current Canvas, make it a little darker/lighter and draw?

**Comment by klaus101** [comment]
To darken or lighten the whole node in such case: i wouldn't prefer, as that would affect all other contents beneath the background too.

And yes, "fully customizable rendering of everything, and not selectively what does not suit" cannot be the job of the metadarkstyle layer.

But i'd agree fibodevy though in so far as it's really not good at all that the unfocused/selected actually won't be recognizable.

And yes, using "DrawThemeBackgroundDark" could be a reasonable way :-)
I tried it, and a small patch like shown below .... wouldn't it be a good compromise??

```
function DrawThemeBackgroundDark(...........
.....
    if Theme[Index] = hTheme then
    begin
      Element:= Index;
.....

      if Element = teTreeview then begin
        if iStateId = TREIS_SELECTEDNOTFOCUS then begin
           LCanvas:= TCanvas.Create;
           try
             LCanvas.Handle:= hdc;
             AColor:= SysColor[COLOR_BTNFACE];
             FillGradient(hdc, Lighter(AColor, 154), Lighter(AColor, 156), pRect, GRADIENT_FILL_RECT_V) // This setting is only as example here!
           finally
             LCanvas.Handle:= 0;
             LCanvas.Free;
           end;
           exit;
        end;
      end;


Would result in something like below (selected focused vs. onfocused):

![selectedfocused_vs_selectedunfocused](https://github.com/zamtmn/metadarkstyle/assets/31130146/4b8864df-76ab-4ea1-b6bf-a715b2994212)

**Comment by klaus101** [comment]
Would result in something like below (selected focused vs. onfocused):
![selectedfocused_vs_selectedunfocused](https://github.com/zamtmn/metadarkstyle/assets/31130146/00adff5e-b048-4b87-a5f9-2413a8c2a37e)

**Comment by fibodevy** [comment]
That is perfect. Thank you, I created a fork with this fix https://github.com/fibodevy/metadarkstyle/commit/e089eb35b4ef5a91c5a9bd0b432da3a0e7e991ef

Here is how it looks now

![GmDjIYRgH6](https://github.com/zamtmn/metadarkstyle/assets/21068718/5134d207-1a87-4a81-bd05-521256231a0c)

**Comment by klaus101** [comment]
Forgot to mention: the execution should be made dependent on Treeview's property "HideSelection" ...
That's not yet herein, but the possibility to do a HideSelection intentionally should be preserved.

**Comment by fibodevy** [comment]
For the purpose of dark IDE it suits well

**Comment by klaus101** [comment]
If you want to see the NotFocused a bit lighter, you might play a bit with the colors, eg.:
 //FillGradient(hdc, Lighter(AColor, 154), Lighter(AColor, 156), pRect, GRADIENT_FILL_RECT_V) ;
   FillGradient(hdc, Lighter(AColor, 144), Lighter(AColor, 146), pRect, GRADIENT_FILL_RECT_V);
It's only an example ...

**Comment by klaus101** [comment]
For to finish the thought about "make it dependent on the property 'HideSelection'":
Afais, from "DrawThemeBackgroundDark" there is no way back - from the given parameters hTheme and hdc – to determine 
the underlying wincontrol (hwnd) for to query this property. Am i right (I’m not quite sure)??

If that's right, the easiest way to do could be imo to use an additional variable - filled within Win32WSWinControlDark.CreateHandle - and to use this remembered variable later (DrawThemeBackgroundDark) as such:
```
  if Element = teTreeview then begin
    if ((tv <> nil) And Not tv.HideSelection) then   // tv = the interims variable
       if iStateId = TREIS_SELECTEDNOTFOCUS then begin

```I tried it and it worked as it should. So, by that, technically the demand could be closed.

@zamtmn, by what you had said i doubt if you were interested in a pull request, but for to go sure i'd like to ask.

**Comment by zamtmn** [comment]
I plan not to change anything for the default "Dark" theme. And make a customizable tree item for the "CustomDark" and other user themes
Sorry for my slowness, a lot of work((

**Comment by klaus101** [comment]
No problem …. Good success for your work!

**Comment by zamtmn** [comment]
I added the CustomDrawTreeViews:boolean parameter to schemes. It false for "Dark", true for "CustomDark" and "White" schemes

**Comment by klaus101** [comment]
Hm, for me with a property "HideSelection" (show selection or not when unfocused) there's by nature nothing about something "custom" in it: it is an essential of the treeview.

What, if one changes the property (in IDE or app): does he need to remember now to change "CustomDrawTreeViews" accordingly too?
That should happen automatically imo (as in my proposed above which is working). What if one has two treeviews (will happen rarely, but might happen!) with two different settings?

I'm not so convinced yet to adapt the change in my work copy.

**Comment by klaus101** [comment]
A typical use case for a "custom" branch imo could be to give room for personal habits or flavors eg. about a specific color.
But for basic properties of the wincontrol the control itself should be in the lead, and not a custom property of a theme. The theme should follow, and not replace properties of the control under the hood with a different name.

**Comment by zamtmn** [comment]
I have added an example of using theme scripts, please take a look.

HideSelection only works if ThemedDraw remove? We should not interfere with the logic of work, let LCL manage this

DefaultDark - this is system color theme, we will fix here only when something is not working correctly, if we just don't like the colors - we optimize them in our theme

**Comment by klaus101** [comment]
Especially when i let the LCL manage this (= show selection at defocus), but, defaultdark themeddrawed, the effect is visually not recognizable, then, in my eyes, it's more than only a don't-like, it's not correct; so i had decided to keep my change within DefaultDark in a local copy (*).

Anyway, sometimes a slightly different opinion may happen, no problem at all!
So i'd like to say that i'm happy that metadarkstyle is working great here in a couple of apps with various components, incl. attabs. virtualstringstree, synedit and many others. Great :-)
For very special visual adjustments I use advancedcustomdraw stuff on app level outside the default draw anyway.
(*) I’m don’t using an installed version but a subset of six files near an app, because sometimes I need minor adapations.

**Comment by zamtmn** [comment]
>>the effect is visually not recognizable
Unfortunately these are the colors set by the windows theme design. You can fix it with this theme script:

```
begin
  Scheme:=DefaultDark;
  CustomDrawTreeViews:=true;
end.
```

I think it can be closed

**Comment by zamtmn** [comment]
I don't see the difference, in LCL it also doesn't work until you turn off tvoThemedDraw
![HideSelection](https://github.com/zamtmn/metadarkstyle/assets/39580611/8e164115-37f2-46c7-b737-4867a3145b5d)
Here's how it looks for me on Win11. Your LCL project works differently?

>That's what my approach does:

This is no good, one variable for many TreeViews?

**Comment by klaus101** [comment]
> (non-dark:) in LCL it also doesn't work until you turn off tvoThemedDraw

You're right here, i'd missed that point earlier 
 
However, with the CustomDrawTreeViews version, which i tested for simpliness by that:
 
       if (Element = teTreeview) then
         DrawTreeView(hTheme,hdc,iPartId,iStateId,pRect,pClipRect) 
       else

i couldn't get the "HideSelection := True"  really to work.
Image: left: CustomDrawTreeViews version (i still see the selection),  right: my version_
![HideSelection](https://github.com/zamtmn/metadarkstyle/assets/31130146/5bb96a56-d878-4a60-becf-dd76c076d3d3)

Win 10 x64, Laz. 3.0RC1, treeview option tvoThemedDraw on.

So I’d prefer to stay at my modification, not a problem at all.

> one variable for many TreeViews?

You're right here too, but this had not been intended. Initially i had assumed this was processed for each control sequentially, but that's wrong i see.  Would need to be improved (the underlying challenge had been that (to my knowledge) one cannot access back from the parameters hTheme and hdc the wincontrol that it belongs to). 

Anyway, as mentioned, for me it's good to use (and myself i've never more than one treeview on a form yet), fibodevy 's request (dark IDE) is served too and all are happy, so of course this can be closed imo :-)

**Comment by zamtmn** [comment]
Ok. Thanks!

**Comment by klaus101** [comment]
Addendum about "one variable for many TreeViews?":
don't worry zamtmn, it's only because i would be very interested in your opinion about:
indeed a very rare use case, but it may happen: multiple treeviews, having different "HideSelection" settings:

but how to determine the treeview object if "htheme" or "hdc" won't allow to identify the referred object, not even indirectly by using any theme function dealing with offset, region, position ("left" and "top" ever will be 0 here)?

The one and only solution i could find is to using an array, where a treeview is identified by it's Canvas.Handle.
And so this is my solution (it works!):

```
var
 .........
  SetWindowSubclass: function(hWnd: HWND; pfnSubclass: SUBCLASSPROC; uIdSubclass: UINT_PTR; dwRefData: DWORD_PTR): BOOL; stdcall;
  tvs : array of TTreeView;


class function TWin32WSWinControlDark.CreateHandle(............
 .........
    if (AWinControl is TCustomTreeView) then begin
      AWinControl.Color:= SysColor[COLOR_WINDOW];
      with TCustomTreeView(AWinControl) do begin
 .........
         if TCustomTreeView(AWinControl) Is TTreeView then begin
           SetLength(tvs, Length(tvs) + 1);
           tvs[High(tvs)] := TTreeView(AWinControl);
        end;

function DrawThemeBackgroundDark(hTheme: HTHEME; hdc: HDC; iPartId, iStateId: Integer; const pRect: TRect;  pClipRect: PRECT): HRESULT; stdcall;
 .........
var
 .........
  Index, Element: TThemedElement;
  tv: TTreeView = nil; i: Integer;
begin
  for Index:= Low(TThemedElement) to High(TThemedElement) do  begin
    if Theme[Index] = hTheme then  begin
      Element:= Index;
 .........
      if Element = teTreeview then begin
         for i := 0 to High(tvs) do  // Find the individual treeview
            if hdc = tvs[i].Canvas.Handle then begin
               tv  :=  tvs[i];
               break;
            end;
        if ((tv <> nil) And Not tv.HideSelection) then
        if iStateId = TREIS_SELECTEDNOTFOCUS then begin
           LCanvas:= TCanvas.Create;
           try
             LCanvas.Handle:= hdc;
             AColor:= SysColor[COLOR_BTNFACE];
             FillGradient(hdc, Lighter(AColor, 154), Lighter(AColor, 156), pRect, GRADIENT_FILL_RECT_V); 
           finally
             LCanvas.Handle:= 0;
             LCanvas.Free;
           end;
           exit(S_OK); // Otherwise doing regular processing!
        end;
      end;
```

Wht do you think? Would be very interested to know.

**Comment by zamtmn** [comment]
Yes, I was thinking of something similar, but it's better to use TDictionary or TMap instead array of TTreeView. This is the only way to indificate own control in uwin32widgetsetdark

Probably something similar can be applied to disable darkstyle in designer. Thanks!

**Comment by zamtmn** [comment]
I add `TreeViewDisableHideSelection` param to global disable HideSelection in trees
try this darkstylecolors file

```
begin
  Scheme:=DefaultDark;
  CustomDrawTreeViews:=true;
  TreeViewDisableHideSelection:=true;
end.
```

**Comment by klaus101** [comment]
Saw it; question (before having tried yet)   =  "one variable for many TreeViews"?

**Comment by klaus101** [comment]
I have no problem with it :-)
