### ISSUE TITLE
Lzazarus Error on opening example

### ISSUE THREAD

**Issue by jonyrh** [zamtmn/metadarkstyle#33]
Hi, zamtmn!

Installed package metadarkstyledsgn226.lpk on Lazarus 2.2.6 (rev lazarus_2_2_6) FPC 3.2.2 x86_64-win64-win32/win64/
After opening example `defaultallowdark` showing error and Lazarus closed...

![Снимок экрана 2023-09-20 073520](https://github.com/zamtmn/metadarkstyle/assets/28771126/1fee8e24-4d6c-49a3-91e1-be433e99b632)

![Снимок экрана 2023-09-20 074344](https://github.com/zamtmn/metadarkstyle/assets/28771126/87898e73-f488-4f1d-8db6-e76ab4d8b172)

**Solution:**

modify `usharedform.lfm`

```
object TreeView1: TTreeView
      Left = 84
      Height = 133
      Top = 187
      Width = 202
      //ShowSeparators = False              // replace 
      Options = [tvoShowSeparators]    // for new version TreeView 
      TabOrder = 1
     ...
    end
```

**Comment by zamtmn** [comment]
Thanks!
