### ISSUE TITLE
Target "Linux" not compiling, solution

### ISSUE THREAD

**Issue by jonyrh** [zamtmn/metadarkstyle#34]
Hi, zamtmn!

If you have meny targets on your one project, you need modify file `uMetaDarkStyle.pas` - add {$IFDEF WINDOWS}
on linux compile error `TDSColors` - unknown...

**solution**

```
{$IFDEF WINDOWS} // add
procedure ApplyMetaDarkStyle(const CS:TDSColors);
{$ENDIF}  // add

implementation

{$IFDEF WINDOWS} // add
procedure ApplyMetaDarkStyle(const CS:TDSColors);
begin
  InitDarkMode;
  Initialize(CS);
  ApplyDarkStyle;
end;
{$ENDIF}  // add
```

**Comment by zamtmn** [comment]
Please create PR, I don't have Linux right now to check

**Comment by jonyrh** [comment]
cross-compile project for windows and linux:
[test_cross.zip](https://github.com/zamtmn/metadarkstyle/files/12671543/test_cross.zip)

**Comment by zamtmn** [comment]
pull request

**Comment by jonyrh** [comment]
linux not need, jast change as in solution

**Comment by zamtmn** [comment]
Please make it in a pull request, I will gladly accept it
