### ISSUE TITLE
Minimizing the IDE from the taskbar button hides the main IDE window permanently

### ISSUE THREAD

**Issue by furious-programming** [zamtmn/metadarkstyle#4]
If I have Lazarus open and I click its button on the taskbar, Lazarus does not minimize itself, but permanently hides its main window (the one with the main menu and component palette). Not only is it impossible to minimize the program in this way, the main window can no longer be restored and the IDE must be restarted.

![ide minimizing problem](https://user-images.githubusercontent.com/8170730/230629282-a0660d02-230b-4deb-bfc9-21d3834e1ed7.gif)

Its impossible to restore the main IDE window in aby way — I tried different keyboard shortcuts. It is also interesting that after the main window disappears, Lazarus cannot be minimized even with `Win+M` shortcut (`Win+D` only works, but after restoring, the main window is gone anyway).

**Comment by cheat-engine** [comment]
Applications made using this also have this behavior

**Comment by zamtmn** [comment]
Please create pr

**Comment by furious-programming** [comment]
Works like a charm, thank you @cheat-engine!
