### ISSUE TITLE
The Chinese characters in the window title will be truncated after enabling dark mode

### ISSUE THREAD

**Issue by ifloppy** [zamtmn/metadarkstyle#44]
The Chinese characters in the window title will be truncated after enabling dark mode

The text used for testing is "你好世界"("Hello World"). Text with both Chinese and English will also be truncated.

I guess this is an encoding problem.

![图片](https://github.com/zamtmn/metadarkstyle/assets/68799904/7960828e-9143-4b81-a4e5-d758c1075d71)
![图片](https://github.com/zamtmn/metadarkstyle/assets/68799904/e8eb5846-5008-4a86-866b-c3a43ef0dbbb)
![图片](https://github.com/zamtmn/metadarkstyle/assets/68799904/d5d19569-1ca0-43ca-804d-242185f3c3c9)
![图片](https://github.com/zamtmn/metadarkstyle/assets/68799904/129f449e-8d83-4bcc-98a1-8b8e09213c5f)

**Comment by zamtmn** [comment]
Please attach minimal example with problem
