### ISSUE TITLE
Add support for non standard controls

### ISSUE THREAD

**Issue by dikcell** [zamtmn/metadarkstyle#46]
How to add darkstyle support for non standard controls, like TRichMemo? 
I tried add richmemo to example project, and its not styled.

**Comment by klaus101** [comment]
I'd had the same problem ... see https://github.com/zamtmn/metadarkstyle/issues/36
with new procedure “TryEnforceDarkStyle” for to be able to request dark style behaviour explicitely.

**Comment by zamtmn** [comment]
Unfortunately, this cannot always be done by this package alone. In this case, you can't do without the code from the outside(( https://github.com/zamtmn/metadarkstyle/issues/36
