### ISSUE TITLE
Failure to compile with FPC 3.3.1(Trunk)

### ISSUE THREAD

**Issue by ifloppy** [zamtmn/metadarkstyle#48]
Hello. I can't compile this package with FPC 3.3.1. Why is this happening?
```
udarkstyleschemes.pas(52,8) Error: Identifier not found "FSet"
```

**Comment by zamtmn** [comment]
I used some loopholes to access the contents of the dictionary, it was recently closed, I create https://gitlab.com/freepascal.org/fpc/source/-/issues/40656 and https://gitlab.com/freepascal.org/fpc/source/-/merge_requests/593 Please give some time, dont use the new versions of FPC, if the patch is not accepted, I will fix it

**Comment by ifloppy** [comment]
I don't know exactly what this code needs to do. I made some simple changes and now it compiles, but I don't know if this will cause unexpected glitches.

![图片](https://github.com/zamtmn/metadarkstyle/assets/68799904/99d52ee9-e87e-406c-a2c2-b5161635efeb)
