### ISSUE TITLE
Compile error: Identifier ApplyDarkStyle not found

### ISSUE THREAD

**Issue by theonlyasdk** [zamtmn/metadarkstyle#52]
Compilation of package fails with the following error
```
Compile package MetaDarkStyle 0.9: Exit code 1, Errors: 1
umetadarkstyle.pas(33,3) Error: Identifier not found "ApplyDarkStyle"
```
![image](https://github.com/user-attachments/assets/37d88dd0-e3f8-4336-8cf5-39d60d41df3c)

Looks like `LCLWIN32` is not defined thus the code inside the `IFDEF` block is greyed out and the unit is not getting imported. Any idea on how to fix this?

**Comment by zamtmn** [comment]
Unfortunately, I won't be able to verify this in the near future. Try replacing $ifdef lclwin32 to $ifdef windows 04.08.2024, 22:11, "TheOnlyASDK" ***@***.***>: Compilation of package fails with the following errorCompile package MetaDarkStyle 0.9: Exit code 1, Errors: 1
umetadarkstyle.pas(33,3) Error: Identifier not found "ApplyDarkStyle"
image.png (view on web)Looks like LCLWIN32 is not defined thus the code inside the IFDEF block is greyed out and the unit is not getting imported. Any idea on how to fix this?—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

**Comment by theonlyasdk** [comment]
![image](https://github.com/user-attachments/assets/a30edcf7-02ef-445b-8f43-751f3ec19fd7)
Now it shows this error:
```
Build IDE: Exit code 2, Errors: 1
udarkstyle.pas(49,34) Error: Cannot find Qt5 used by uDarkStyle. Enable flag "Use Unit" of unit Qt5 in package LCL.
```

**Comment by zamtmn** [comment]
You try compile for qt? try to win32 04.08.2024, 22:49, "TheOnlyASDK" ***@***.***>: image.png (view on web)Now it shows this error:Build IDE: Exit code 2, Errors: 1
udarkstyle.pas(49,34) Error: Cannot find Qt5 used by uDarkStyle. Enable flag "Use Unit" of unit Qt5 in package LCL.

**Comment by theonlyasdk** [comment]
No, not trying to compile for Qt, here's my Lazarus build configuration:
![image](https://github.com/user-attachments/assets/f36d1a1f-5d19-4311-a7c3-1dc8b05c1948)
(it says win32/64)

**Comment by theonlyasdk** [comment]
Hello! Any solutions yet? From what I've heard from others, this package compiles fine on lazarus 2.4 and 2.6. But for me, it does not compile on Lazarus 3.4 and shows me the above error.

**Comment by zamtmn** [comment]
I just checked it out - everything works with Lazarus3.4x64.
Give more details - where did you get Lazarus, where did you get MDS?
Try it with a clean Lazarus installation?

**Comment by theonlyasdk** [comment]
I got the 64 bit version of lazarus from here: https://www.lazarus-ide.org/index.php?page=downloads
I got MDS from online package manager
I'm gonna try with a clean Lazarus install

**Comment by zamtmn** [comment]
Try last mds from github?

**Comment by theonlyasdk** [comment]
Nope, doesn't work. Clean install, MDS from latest commit from GitHub, still shows the error for Qt. 
I think it's something related to the macros in the following piece of code:
```pascal
{$IFDEF WINDOWS}
uses
    {IF DEFINED(LCLQT5)}
      uDarkStyle,
    {ENDIF}
    uDarkStyleParams,
    {$IFDEF LCLWIN32}
    uWin32WidgetSetDark,
    {$ENDIF}
    uDarkStyleSchemesLoader;
{$ENDIF}   
```
I'm assuming `LCQT5` is getting defined somewhere, causing it to include `uDarkStyle` instead of `uWin32WidgetSetDark`

**Comment by theonlyasdk** [comment]
Okay, forget about the above message. It now compiles fine, and I get the dark style option in Tools > Options > Dark mode.
I tried setting it to force dark, and restarted the IDE, but nothing happened. I installed both `metadarkstyle.lpk` and `metadarkstyledsgn.lpk` on Lazarus 3.4

**Comment by theonlyasdk** [comment]
Okay, finally. After hours of fiddling with it, I got it to work. I installed it from online package manager, and it magically worked! Thanks for the help @zamtmn

**Comment by zamtmn** [comment]
I advise you not to use ORM, get everything from the original sources. The primary source is this repository

**Comment by theonlyasdk** [comment]
I've a question. Where does ORM pull the sources from? Do you upload a specific version to it or does it pull it from this repo?
