### ISSUE TITLE
Does not fully work when using a packer like UPX 

### ISSUE THREAD

**Issue by PictureWilly** [zamtmn/metadarkstyle#55]
Great Dark Mode on Windows. Many THANKS!

Unfortunately it doesn't really work if the app.exe is packed with a packer like [UPX](https://github.com/upx/upx). 

Here the issue shown with the demo app. DoubleCommander packed with UPX has the same issue.

![Issue](https://github.com/user-attachments/assets/7a61fecc-cb1d-490a-8a7d-e9fca4e2d31e)

Hope you can fix this as it is essential to wrap some apps with packers.

**Comment by zamtmn** [comment]
Unfortunately I won't be able to fix it.

**Comment by zamtmn** [comment]
I think the point is that the import tables are different for the compressed image and the decompressed image, My knowledge is not enough to solve this issue. If you find a solution, I will consider it and accept it.

**Comment by zamtmn** [comment]
Fixed in 6922aa977499d3d3500fd892cb64f09fe0cbabb2 please test

**Comment by zamtmn** [comment]
yes, not work. try 430785928a649cc3c6f40a8aa230b5da8873ec46

**Comment by zamtmn** [comment]
Thanks!
