### ISSUE TITLE
Trouble with fix #5 / April 10 -> Update after TListView Header fix April 11th

### ISSUE THREAD

**Issue by klaus101** [zamtmn/metadarkstyle#6]
@zantmn, please let's have a short break. I tried the newly committed version (Apr. 10)
and had before a fine working version based on commit Apr. 07.
I was surprised that the new version does contain many changes regarding the listview and so i tested.
I see regressions here. Partially it behaved like an old version (not good readable colors on column header, no sort indicator ...). (With custmm listview). Like as long ago.

Actually i tried the new "uwin32widgetsetdark.pas" stand-alone, means: together with the original files as coming from DC.

The version from Apr 7 had been fine. Following benefits:
- listview column header bg and font color good; sort indicator is visible.
- Additional benefit differently to the versions before "Try fix TListView 2" is:
 I did not even need a dedicated "SetWindowTheme(Handle, 'DarkMode_Explorer', NIL);" statement.
 And: for ListViews in subforms i did not even dedicated includes, it worked directly out of the box via theme.
 All those benefits about the ListView gone lost.
 
 Why only that had been changed? **The version with Try fix TListView 2 was fine**
I attach the version i actually successfully use based on yours Apr. 07 (good) as info (comments why and where i changed are inside).
 
 Moreover: regarding the status bar divider nothing did change with the new version. Although the functionality already had been (nearly ready) in there Apr, 07.
 It would have required only a very minimal adaption here. See the comments inside my attachment.
 But COLOR_BTNFACE won't have any effect. Use at least COLOR_GRAYTEXT - or something else what will be visisble.
 I my self was not successful yet to apply a seconde vertical line for to have the shadow effect
 
 I'm very confused and got  lost here .... something went wrong. See image "unreadable" vs. "readable":

![custiomlistview_colheader_apr10_unreadable](https://user-images.githubusercontent.com/31130146/231089494-41cc3928-780c-404b-ad83-35edddbba597.jpg)

![custiomlistview_colheader_apr07_readable](https://user-images.githubusercontent.com/31130146/231089492-6174befa-a602-476b-8150-b98f050aba73.jpg)
[zamtmn_apr07_modified_uwin32widgetsetdark.zip](https://github.com/zamtmn/metadarkstyle/files/11197875/zamtmn_apr07_modified_uwin32widgetsetdark.zip)

**Comment by zamtmn** [comment]
it seems too black for me, I tried to make the title look like VTV, but it really didn't work out

**Comment by klaus101** [comment]
Right about "too black". May be. But what is the benefit of having a nice, "theme-compliant" background color when text and sort indicator are not readable?
I think it's the best actually we can have, unless one finds a possibility to change bg color **and** text color as well.
